### ISSUE TITLE
the code

### ISSUE THREAD

**Issue by 213s** [ispc-lab/GLC#2]
Hello, I am very interested in your article, I would like to know what are the functions of these two parts, thank you.
![image](https://github.com/ispc-lab/GLC/assets/106941146/0ad8d8b7-6405-4133-b24b-297f18ec112f)

**Comment by sanqingqu** [comment]
Thank you for your interest in our work.

The `train_source.py` file is used to pre-train the source model, while `train_target.py` is used to achieve model adaptation under category shift without accessing the source data.

**Comment by 213s** [comment]
Thank you very much for your reply

**Comment by sanqingqu** [comment]
You're welcome. 
Since you have no further questions, I will close this issue.
