### ISSUE TITLE
article

### ISSUE THREAD

**Issue by 213s** [ispc-lab/GLC#3]
Hello, I would like to ask whether this article has been accepted by cvpr or

**Comment by sanqingqu** [comment]
Thanks for your great interest in our work. 
Yes, definitely, our work has been accepted by CVPR-2023. Here is an official link to our paper, https://openaccess.thecvf.com/content/CVPR2023/papers/Qu_Upcycling_Models_Under_Domain_and_Category_Shift_CVPR_2023_paper.pdf
