### ISSUE TITLE
training OPDA for DomainNet

### ISSUE THREAD

**Issue by Kaiseem** [ispc-lab/GLC#5]
Dear authors, thanks for your great work.
Can you provide the image_unida_list.txt for DomainNet?
Meanwhile, is the setup for DomainNet and VisDA the same? e.g., training epochs for source and target. Otherwise could you detail the training parameters?
Looking forward your reply. Thanks a lot.

**Comment by sanqingqu** [comment]
Thank you for your great interest in our work.
I have added DomainNet's `image_unida_list.txt` to this repo. In addition, I have updated the OPDA script to include DomainNet.
