### ISSUE TITLE
domainnet加载的一个小问题

### ISSUE THREAD

**Issue by bamboosir920** [ispc-lab/GLC#6]
model_config.py中，因为domainnet貌似只用了三个domain，154行应该更改为range(3)，否则会超出list
 ![image](https://github.com/ispc-lab/GLC/assets/53424562/3913e803-0f70-47ad-9008-ecc1bae1d066)

**Comment by sanqingqu** [comment]
感谢提醒。当时release代码时，引入了这个小bug，抱歉。
